apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"hello-world","namespace":"default"},"spec":{"selector":{"matchLabels":{"run":"hello-world"}},"template":{"metadata":{"labels":{"run":"hello-world"}},"spec":{"containers":[{"image":"scias23/jm-lab9:latest","name":"hello-world","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2024-02-08T07:19:24Z"
  generation: 3
  name: hello-world
  namespace: default
  resourceVersion: "5556"
  uid: 7393ad2a-457f-4523-95e5-6edfe1779652
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-world
    spec:
      containers:
      - image: scias23/jm-lab9:latest
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-08T07:21:58Z"
    lastUpdateTime: "2024-02-08T07:21:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-02-08T07:19:24Z"
    lastUpdateTime: "2024-02-08T07:21:58Z"
    message: ReplicaSet "hello-world-58879c49d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
